default_xp: 1

categories:
  AXE:
    OAK_LOG: 1
    SPRUCE_LOG: 1
    BIRCH_LOG: 1
    JUNGLE_LOG: 1
    ACACIA_LOG: 1
    DARK_OAK_LOG: 1
    MANGROVE_LOG: 1
    CHERRY_LOG: 1
    BAMBOO_BLOCK: 1
    COCOA: 2

  PICKAXE:
    STONE: 1
    COBBLESTONE: 1
    DEEPSLATE: 2
    COBBLED_DEEPSLATE: 2
    BASALT: 2
    SMOOTH_BASALT: 2
    TUFF: 2
    COAL_ORE: 2
    DEEPSLATE_COAL_ORE: 3
    COPPER_ORE: 3
    DEEPSLATE_COPPER_ORE: 4
    IRON_ORE: 4
    DEEPSLATE_IRON_ORE: 5
    GOLD_ORE: 5
    DEEPSLATE_GOLD_ORE: 6
    REDSTONE_ORE: 4
    DEEPSLATE_REDSTONE_ORE: 5
    LAPIS_ORE: 4
    DEEPSLATE_LAPIS_ORE: 5
    DIAMOND_ORE: 10
    DEEPSLATE_DIAMOND_ORE: 12
    EMERALD_ORE: 10
    DEEPSLATE_EMERALD_ORE: 12
    NETHER_QUARTZ_ORE: 3
    NETHER_GOLD_ORE: 4

  HOE:
    WHEAT: 1
    CARROTS: 1
    POTATOES: 1
    BEETROOTS: 1
    NETHER_WART: 1
    SUGAR_CANE: 1
    SWEET_BERRY_BUSH: 1
    BAMBOO: 1

  SHEARS:
    VINE: 1
    GLOW_LICHEN: 1
    OAK_LEAVES: 1
    SPRUCE_LEAVES: 1
    BIRCH_LEAVES: 1
    JUNGLE_LEAVES: 1
    ACACIA_LEAVES: 1
    DARK_OAK_LEAVES: 1
    MANGROVE_LEAVES: 1
    CHERRY_LEAVES: 1
    AZALEA_LEAVES: 1
    FLOWERING_AZALEA_LEAVES: 1

  SHOVEL:
    GRASS_BLOCK: 1
    MYCELIUM: 2
